Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -61,15 +61,20 @@ jobs:
       - name: Build C programs
         run: |
           source /opt/intel/sgxsdk/environment
-          for dir in app/ecall_asm app/crypto-app app/speed-test-sdk app/bare-step app/ecall_ptr app/bare-crypto-app; do
-            echo "Building in $dir"
-            cd $dir
-            make
-            if [ -f "app" ]; then
-              echo "Binary 'app' created in $dir"
+          for dir in app/*/; do
+            if [ -f "$dir/Makefile" ]; then
+              make clean
+              echo "Building in $dir"
+              cd "$dir"
+              make
+              if [ -f "app" ]; then
+                echo "Binary 'app' created in $dir"
+              else
+                echo "Error: Binary 'app' not found in $dir"
+                exit 1
+              fi
+              cd -
             else
-              echo "Error: Binary 'app' not found in $dir"
-              exit 1
+              echo "Skipping $dir (no Makefile)"
             fi
-            cd -
           done
